apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    app: hello-world-app
spec:
  containers:
  - name: first
    image: "gcr.io/google-samples/hello-app:2.0"
---
apiVersion: v1
kind: Pod
metadata:
  name: secondpod
  labels:
    app: hello-world-app
spec:
  containers:
  - name: second
    image: "gcr.io/google-samples/hello-app:2.0"
